### ISSUE TITLE
Error 1004 when build a package

### ISSUE THREAD

**Issue by OlivierJourdan** [vipm-io/vipm-desktop-issues#85]
**Short Description of the Bug (in one or two sentences)**

I get this error when building a VIP.

<img width="530" height="422" alt="Image" src="https://github.com/user-attachments/assets/469c206f-e77c-4419-927c-837765b38a96" />

I've successfully built the package once, and I can see what I did to break the process.
Getting back to the previous commits of the vipb doesn't solve the problem.

**Version Information**

VIPM Version and Build:
2024.1 f1 and 2025.3

Operating System Version:
Windows 10

LabVIEW Version:
LV2020

LabVIEW Bitness:
32-bit 

Virtualization or Processor Version Information
VM

**Steps To Reproduce**
Build the vip of this project --> https://gitlab.com/wovalab/open-source/data-visualization-toolkit-for-labview

**Comment by jimkring** [comment]
I get the same error on my machine.

> Error 1004 occurred at Open VI Reference in Save VIs to Destination__ogb.vi->Build Application__ogb.vi->Build Application from Build File__ogb.vi->Build Application from Build File__ogb.vi.ProxyCaller  Possible reason(s):  LabVIEW: (Hex 0x3EC) The VI is not in memory.  Error Conditions: Private Save VI Name: "Data Visualization Toolkit for LabVIEW.lvlib:HTTP Client Extensions.lvlib:GET Async.lvclass:Read Error.vi" VI Path: "C:\Users\jki\AppData\Local\Temp\vpbtmp\src\LabVIEW\vi.lib\Wovalab\Data Visualization Toolkit for LabVIEW\HTTP Client Extensions\HTTP GET Async\Read Error.vi"  To load a VI into memory with the Open VI Reference function, a path must be wired for the VI Path input.  VI Name: Data Visualization Toolkit for LabVIEW.lvlib:HTTP Client Extensions.lvlib:GET Async.lvclass:Read Error.vi

**Comment by OlivierJourdan** [comment]
I'll say that it's good news 😅

**Comment by Tom-McQuillan** [comment]
As a side note:
I received this error on a completely unrelated codebase last week (nothing to do with VIPM). The error was implying the static VI reference I was using wasn't loading the referenced VI into memory when the top-level VI loaded - which is concerning. (switching from SVR -> Name, to SVR -> Path resolved it for me).

Please could you humor me and verify you can run the top level VIs from a "cold start"?

I only have a sample size of 1, but the issue I ran into last week with the SVR (that resulted in this error) has made me suspicious.

**Comment by OlivierJourdan** [comment]
The code runs fine from a "cold start".

I did some more tests this morning. I remove the Read Error.vi the error is pointing to. I get the same error, the 1004, but with another VI.

<img width="538" height="424" alt="Image" src="https://github.com/user-attachments/assets/5f6c684c-6995-476c-b042-4af2a565d6ed" />

It seems there's an issue with a bunch of VIs. There's actually an SVR in the code. I'll put the VI directly in the code to see what happens.

Still, I don't understand why I managed to build the VIP once and why I can build a similar toolkit. I can't see what I changed.

**Comment by OlivierJourdan** [comment]
For the record, I still have the error after placing the dynamically called VI directly in the code.

**Comment by OlivierJourdan** [comment]
Hello @Tom-McQuillan,
Did you have the opportunity to delve further into this issue?

**Comment by Tom-McQuillan** [comment]
For those playing along at home, here are my raw troubleshooting notes:

TL;DR: Not working, but I have a lot more datapoints
```
I was able to build a package by not mass compiling. I'm installing it now to see if it's still functional
Although there was an error with the post install script.

When I try to open the post install build script in LabVIEW it is searching for things.
--------------------
Just for testing I have removed the post install script (and re-enabled mass compile). VI in question: C:\code\data-visualization-toolkit-for-labview\Resources\Post-Install Custom Action.vi

This resulted in the same Not in Memory Error.
--------------------
New test, same as above but selected Do Not Compile
It builds, Installed, Palette is broken.
The palette is a core thing that breaks when you do not mass compile.
--------------------

When I mass compile the sourcecode folder (LabVIEW >Tools >advanced>Mass Compile) I don't get any errors.
--------------------
I noticed you are renaming enabled. I have disabled that and enabled mass compile. - same Not in Memory Issue
--------------------

Excluding HTTP Client Extension and Vega Processor from the package. The package built

--------------------

Re-included Vega Processor - the error happens
--------------------
Included HTTP Client Extensions, Excluded Vega Processor - the error happens
```

**Comment by Tom-McQuillan** [comment]
There is a potential fix in place for `VIPM 2026Q1 Preview 2` (to be released in the next few weeks)

**Comment by MichaelAivaliotis** [comment]
I just ran across this issue today with the latest VIPM (2025.3 f1)
This is a new package, so I have never built it before.

<img width="535" height="423" alt="Image" src="https://github.com/user-attachments/assets/676f3142-217b-445b-b586-1ffa7cfffa1c" />

**Comment by Tom-McQuillan** [comment]
@MichaelAivaliotis I released an update today that should address that (if it's the same issue as @OlivierJourdan ).

- Head to https://docs.vipm.io/preview/ to download the latest preview (VIPM 2026Q1 Preview 2)
- Goto Options > Feature Previews, and check the bottom two items

Let me know how you get on.

**Comment by MichaelAivaliotis** [comment]
Unfortunately the Preview 2 build didn't resolve the issue I was having.
This is a blocking issue for me. I can provide source code offline for debugging if needed.

**Comment by Tom-McQuillan** [comment]
@MichaelAivaliotis created a specific issue for you here: https://github.com/vipm-io/vipm-desktop-issues/issues/95

**Comment by Tom-McQuillan** [comment]
This issue has been resolved in the latest VIPM Preview release (and will be included in VPM 2026Q1)
