### ISSUE TITLE
VIPM CLI with Dragon Files

### ISSUE THREAD

**Issue by wheeller123** [vipm-io/vipm-desktop-issues#89]
The cli version of vipm doesn't seem to work as expected with .dragon files

VIPM Version and Build: `VIPM Q1 Preview 1`

Operating System Version: Windows 10

LabVIEW Version: 2023 Q3
LabVIEW Bitness: 64-bit LabVIEW
Virtual Machine: Yes

**Steps To Reproduce**
1. I downloaded the latest "VIPM Q1 Preview 1"
2. I create a .dragon file according to https://dragon.vipm.io/features/#toml-file-format

<img width="333" height="162" alt="Image" src="https://github.com/user-attachments/assets/cca0b3c3-2b43-4381-bf41-aea6efbd14c7" />

3. I ran the cli commend "vipm install path_to_dragon_file

**Expected behavior**
OpenG package installed but it does not and throws error 

<img width="641" height="110" alt="Image" src="https://github.com/user-attachments/assets/36558fab-e59b-4e9f-8854-dc819a4e195f" />

**Comment by Tom-McQuillan** [comment]
@wheeller123 , you're the first to give feedback on the preview release! thank you very much for reporting this issue.
I will review this and get back to you

**Comment by Tom-McQuillan** [comment]
For testing could you try `vipm list <dragon file>`? I want to see how the CLI reads the file you created.

**Comment by wheeller123** [comment]
Hi Tom,

This is what I get when I run that command

<img width="1430" height="242" alt="Image" src="https://github.com/user-attachments/assets/7a650aa6-5231-439b-bac2-2e9fcc1be648" />

**Comment by Tom-McQuillan** [comment]
Cheers, are you able to send me that file (drag it into a github comment) or send me a repoducer?

**Comment by wheeller123** [comment]
Hey Tom, It won't let me upload the file for some reason but here are the contents

```
[project]
labview-version = 2023
vipc = ""

[vipm.dependencies]
oglib_file = "6.0.2.28"
```

**Comment by wheeller123** [comment]
Here you go, worked when I added to a zip

[lv_cicd_tests_project.zip](https://github.com/user-attachments/files/23344044/lv_cicd_tests_project.zip)

**Comment by jimkring** [comment]
@wheeller123 are you able to install this package from within VIPM Desktop (main UI)?

What happens if you try `vipm install --labview-version 2023 oglib_file@6.0.2.28`?

**Comment by wheeller123** [comment]
Hi Jim,

This is the output I get when running that command

```
C:\Users\jwhelan2>vipm install --labview-version 2023 oglib_file@6.0.2.28
Installing 1 package
Using LabVIEW 2023 (64-bit)
install: 0 (0/1; 0%) - Installing packagesError: Package 'Not found: Package 'oglib_file' version '6.0.2.28' not found. Available versions: 2.1-1, 4.0.1.22, 3.0.1-1, 2.6-1, 4.0.0.20, 2.8-2, 2.5-1, 2.8-1, 2.7-1, 2.2-1, 2.0-1, 2.1-2, 2.4-1, 2.3-1' not found
```

**Comment by wheeller123** [comment]
I also tried using a vipc file and this worked fine (even if the logs say "No packages were installed.")

Packages can be seen installed
<img width="802" height="211" alt="Image" src="https://github.com/user-attachments/assets/56b54a31-e9a2-4556-aa70-e5c9c7a49082" />

Command used: 

```
$ echo "Installing Missing Packages"
Installing Missing Packages
$ vipm install "$CI_PROJECT_DIR/requirements.vipc"
install: 0 (0/1; 0%) - Applying VIPC file: C:\gitlab-runner\builds\LfjwScM2s\0\SBR\test_platform_training_area\cicd_training\lv_2023_build_server_tests\requirements.vipc
Auto-detected LabVIEW 2023 (64-bit)
Applying VI Package Configuration "C:\gitlab-runner\builds\LfjwScM2s\0\SBR\test_platform_training_area\cicd_training\lv_2023_build_server_tests\requirements.vipc" in 
install: 100 (1/1; 100%) - Installation complete                                
✓ Installed 0 packages from LabVIEW 2023 (64-bit) in 101.6s
No packages were installed.
$ echo "Missing Packages Installed"
Missing Packages Installed
Cleaning up project directory and file based variables
00:01
Job succeeded
```
Here is the vipc file I used
[requirements.zip](https://github.com/user-attachments/files/23357700/requirements.zip)

<img width="769" height="240" alt="Image" src="https://github.com/user-attachments/assets/bf452e8d-ae28-423a-ab03-33f49e3e134c" />

**Comment by jimkring** [comment]
@wheeller123 what happens if you now uninstall it from the main package list and then try the command line again?

Or, you can try uninstalling from the cli...

```
vipm uninstall --labview-version 2023 oglib_file@6.0.2.28
```

And reinstalling...

```
vipm install --labview-version 2023 oglib_file@6.0.2.28
```

BTW, I am unable to reproduce this on my computer. I was able to install `oglib_file@6.0.2.28` on the first try.

**Comment by wheeller123** [comment]
Hi Jim and Tom,

I'm not exactly sure what's changed but it seems to be working now. Instead of installing VIPM via the execuatbe, I am using curl as [advised by Tom](https://github.com/vipm-io/vipm-desktop-issues/issues/90). 

Curl Installation Details
```
C:\Users\jwhelan2>vipm about
VIPM Desktop Version: 2026.1.0
VIPM CLI Version: 2026.1.0
Installation ID: 6837F3C38E129663E2F33C46356481D8
Edition: Free
Build Date: 2025-10-20
Build Number: 3289
Copyright: Copyright 2006-2025 JKI. All Rights Reserved.
Support: https://www.jki.net/vipm/support
```

Note I still get an error message "timed out after 162s" but the packages installed. Is there a way to increase the timeout?
<img width="1278" height="377" alt="Image" src="https://github.com/user-attachments/assets/3753e692-3564-416f-9163-14f1cd024d7f" />

VIPC Files are also working

<img width="1209" height="358" alt="Image" src="https://github.com/user-attachments/assets/d11961e7-1e6f-4776-ba62-3e30a083c035" />

However Dragon files still are not working

<img width="1278" height="373" alt="Image" src="https://github.com/user-attachments/assets/659e9c59-5430-430f-9d2a-b4f5077f4452" />

**Comment by jimkring** [comment]
Hi @wheeller123 -- I just checked and there is no `--timeout <seconds>` parameter supported yet. Either way, we need to address the timeout error.  We'll dig into the dragon file issue, too.  Stay tuned...

**Comment by wheeller123** [comment]
Thanks Jim, anything I can help with give me a shout

**Comment by jimkring** [comment]
@wheeller123 we are actively working on a fix, and it’ll definitely be forthcoming. Would be happy for your help in testing as soon as we have a new build suitable for sharing.

**Comment by jimkring** [comment]
@wheeler123, we will be publishing a new preview release in the next couple of days, which includes a possible fix for this issues. Thanks for your patience and help testing.

**Comment by jimkring** [comment]
@wheeller123 I believe this is fixed in Preview 2. You can download+install that new version using the instructions here: https://docs.vipm.io/preview/

Please confirm if that's working for you.

**Comment by wheeller123** [comment]
Hi @jimkring sorry for the delay in getting back to you. I just tried Preview 3 and I can see the previous errors are no longer an issue, thank you! We still have the timeout issue for dragon files with multiple dependencies. Should I raise a new ticket for this? Dragon file also attached 

[XCP Custom Device.zip](https://github.com/user-attachments/files/23692171/XCP.Custom.Device.zip)

```
C:\Users\adasdev1>vipm install "C:\gitlab-runner\builds\LfjwScM2s\0\SBR\test_frameworks\libraries\veristand_libraries\XCP_Custom_Device\Source\XCP Custom Device.dragon"
Processing 1 Dragon file
Using LabVIEW version: (unspecified)
Processing Dragon file "C:\gitlab-runner\builds\LfjwScM2s\0\SBR\test_frameworks\libraries\veristand_libraries\XCP_Custom_Device\Source\XCP Custom Device.dragon"
install: 0 (0/1; 0%) - Processing Dragon file: C:\gitlab-runner\builds\LfjwScM2s\0\SBR\test_frameworks\libraries\veristand_libraries\XCP_Custom_Device\Source\XCP Custom Device.dragon
⚠️  Warning: Dragon file contains NIPM dependencies which are not supported by VIPM CLI
Using LabVIEW 2023 (64-bit) from Dragon
install: 100 (1/1; 100%) - Installing packages
Error: Operation 'VIPM command 'package_install'' timed out after 162s
```

**Comment by jimkring** [comment]
@wheeller123 Yes, please--if you can create a new issue for the time-out installing a .vipc, we'll be sure to track it. Thanks!
